library(readxl)
Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations <- read_excel("E:/kamagyana/Computing/DARET/Assignments/Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations.xlsx")
View(Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations)
head(ns)
biceps <- Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations
library(foreign)
library(nnet)
library(ggplot2)
library(reshape2)
library(caret)
colnames(biceps)
bicepsdata <- biceps[,-c(1:6,11:36,49:57,68:82,86:111,124:149)]
colnames(bicepsdata)
logref <- relevel(bicepsdata$classe,ref = "A")
library(nnet)
bicepfit <- multinom(classe~.,data = bicepsdata)
summary(bicepfit)
z <- summary(bicepfit)$coefficients/summary(bicepfit)$standard.errors
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
w <- (summary(bicepfit)$coefficients)^2/(summary(bicepfit)$standard.errors)^2
sum(is.na(bicepsdata))
library(MICE)
tempData <- mice(bicepsdata,m=5,maxit=50,meth='pmm',seed=500)
install.packages("mice")
library(mice)
tempData <- mice(bicepsdata,m=5,maxit=50,meth='pmm',seed=500)
compbicepsdata <- complete(tempData,1)
sum(is.na(compbicepsdata))
colnames(compbicepsdata)
bicepfitcomp <- multinom(classe~.,data = compbicepsdata)
zc <- summary(bicepfitcomp)$coefficients/summary(bicepfit)$standard.errors;pc <- (1 - pnorm(abs(zc), 0, 1)) * 2
wc <- (summary(bicepfitcomp)$coefficients)^2/(summary(bicepfitcomp)$standard.errors)^2
write.csv(biceps,file = "D:/kamagyana/Computing/DARET/Assignments/biceps.csv",row.names=FALSE)
write.csv(bicepsdata,file = "D:/kamagyana/Computing/DARET/Assignments/bicepsdata.csv",row.names=FALSE)
write.csv(compbicepsdata,file = "D:/kamagyana/Computing/DARET/Assignments/compbicepsdata.csv",row.names=FALSE)
write.csv(bitrain,file = "D:/kamagyana/Computing/DARET/Assignments/bitrain.csv",row.names=FALSE)
write.csv(bitest,file = "D:/kamagyana/Computing/DARET/Assignments/bitest.csv",row.names=FALSE)
fit1 <- multinom(classe~.,data = compbicepsdata[,-52])
summary(fit1)
fit2 <- multinom(classe~.,data = bitrain[,-52])
summary(fit2)
pred1 <- predict(fit1,compbicepsdata[,-52])
pred2 <- predict(fit2,bitest[,-52])
pred1 <- cbind(compbicepsdata,pred1)
pred2 <- cbind(bitest,pred2)
confusionMatrix(pred1$classe,pred1$pred1)
colnames(pred1)
nrows(pred1)
nrow(pred1)
ncol(pred1)
length(pred1$classe)
length(pred1$pred1)
confusionMatrix(pred1$classe,pred1$pred1)
table(pred1$classe)
table(pred1$pred1)
class(pred1$classe)
pred2$classe <- as.factor(pred2$classe)
pred2$pred2 <- as.factor(pred2$pred2)
confusionMatrix(pred1$classe,pred1$pred1)
confusionMatrix(pred2$classe,pred2$pred2)
install.packages("ResourceSelection")
library(ResourceSelection)
install.packages("generalhoslem")
library(generalhoslem)
#hosmer-lemeshow test
chisq.test(table(pred1$classe),table(pred1$pred1))
chisq.test(table(pred2$classe), table(pred2$pred2))
varImp(fit1)
varImp(fit2)
anova(fit1,fit2,test = "Chisq")
install.packages("pscl")
library(pscl)
pR2(fit1)["McFadden"]
pR2(fit2)["McFadden"]
library(caret)
library(rpart)
train_control <- trainControl(method="cv", number=10)
model <- train(classe~.data=bitrain,trContol = train_control,method ="glm")
model <- train(classe~., data = bitrain, trContol = train_control,method ="glm")
